name = "BatchOptInterface"
uuid = "75110529-b25f-4ac5-b01f-d734aa829793"
version = "0.1.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[weakdeps]
FlexPOI = "0ce12081-1996-43f5-a93d-beb8dcaefcb1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ParametricOptInterface = "0ce4ce61-57bf-432b-a095-efac525d185e"

[extensions]
BatchOptInterfaceFlexPOIExt = "FlexPOI"
BatchOptInterfaceJuMPExt = "JuMP"
BatchOptInterfacePOIExt = "ParametricOptInterface"

[sources]
FlexPOI = {path = "../FlexPOI.jl"}

[compat]
FlexPOI = "0.1"
HiGHS = "1"
JuMP = "1"
MathOptInterface = "1"
ParametricOptInterface = "0.15"
julia = "1.10"

[extras]
FlexPOI = "0ce12081-1996-43f5-a93d-beb8dcaefcb1"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ParametricOptInterface = "0ce4ce61-57bf-432b-a095-efac525d185e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FlexPOI", "HiGHS", "JuMP", "ParametricOptInterface", "Test"]
